import Head from "next/head";
import Sidebar from "../../components/Sidebar";

export default function Home() {
  return (
    <div className="flex">
      <Head>
        <title>NgobrolApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      <div className="items-center justify-center flex-1 hidden h-screen bg-gray-300 lg:flex">
        <p className="text-3xl font-medium text-white">
          Start a new chat with someone
        </p>
      </div>
    </div>
  );
}
